# Generated by Django 4.1.4 on 2022-12-16 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Notas',
        ),
    ]
